### ISSUE TITLE
[make_summary] Filters disappear when editing script-generated card from dashboard

### ISSUE THREAD

**Issue by hellpe** [OpenSourcePolitics/data_utils#18]
Steps to reproduce:
- Run `make_summary.py` to generate cards
- Add a generated card to a dashboard (e.g. https://metabase.osp.cat/dashboard/431-magazine-linfo-enquete-de-lectorat)
- Click on the card title to open the card page (e.g. https://metabase.osp.cat/question/4813-2-linfo-est-un-magazine-mensuel-le-recevez-vous)

Observed result:
The question filter disappears and answers are displayed in the card graph.

(screenshots pending)

**Comment by Dynnammo** [comment]
@hellpe nothing found after many investigations, since the original problem was the ordering issue I consider this one as not relevant for now.
